import Foundation
import XCTest
@testable import MaroonCompass

/// These images are generated by Fixtures/generate.py. This exercises Vision plus the
/// deterministic OCR fallback only; it does not measure Foundation Models accuracy.
final class ScheduleImageEvaluationTests: XCTestCase {
    private struct Meeting {
        let days: Set<Weekday>
        let start: String
        let end: String
        let building: String
        let room: String
    }

    private struct Course {
        let code: String
        let title: String
        let section: String
        let meetings: [Meeting]
    }

    private struct Fixture {
        let file: String
        let courses: [Course]
    }

    func testSyntheticImagesReportFieldLevelOCRAccuracy() async throws {
        let fixtures: [Fixture] = [
            Fixture(file: "clean-light.png", courses: [
                Course(code: "MATH 251", title: "Calculus 3", section: "502", meetings: [
                    Meeting(days: [.tuesday, .thursday], start: "5:30 PM", end: "6:45 PM", building: "BLOC", room: "1O9"),
                    Meeting(days: [.wednesday], start: "09:10", end: "10:00", building: "BLOC", room: "169")
                ]),
                Course(code: "CHEM 117", title: "General Chemistry Laboratory", section: "541", meetings: [
                    Meeting(days: [.tuesday], start: "11:10 AM", end: "2:00 PM", building: "HELD", room: "302")
                ])
            ]),
            Fixture(file: "dark-compact.png", courses: [
                Course(code: "POLS 207", title: "State and Local Government", section: "502", meetings: [
                    Meeting(days: [.monday, .wednesday, .friday], start: "09:10", end: "10:00", building: "HECC", room: "100")
                ]),
                Course(code: "ENGR 102", title: "Engineering Lab I", section: "505", meetings: [
                    Meeting(days: [.monday], start: "17:10", end: "18:00", building: "ZACH", room: "353"),
                    Meeting(days: [.monday], start: "18:01", end: "19:00", building: "ZACH", room: "353")
                ])
            ]),
            Fixture(file: "cropped-missing-column.png", courses: [
                Course(code: "POLS 207", title: "State and Local Government", section: "502", meetings: []),
                Course(code: "MATH 251", title: "Calculus 3", section: "502", meetings: [
                    Meeting(days: [.tuesday, .thursday], start: "5:30 PM", end: "6:45 PM", building: "BLOC", room: "1O9")
                ])
            ]),
            Fixture(file: "blurry-low-resolution.png", courses: [
                Course(code: "CHEM 117", title: "General Chemistry Laboratory", section: "541", meetings: [
                    Meeting(days: [.tuesday], start: "11:10 AM", end: "2:00 PM", building: "HELD", room: "302")
                ]),
                Course(code: "MATH 251", title: "Calculus 3", section: "502", meetings: [
                    Meeting(days: [.wednesday], start: "09:10", end: "10:00", building: "BLOC", room: "169")
                ])
            ]),
            Fixture(file: "unrelated-text.png", courses: [
                Course(code: "MATH 251", title: "Calculus 3", section: "502", meetings: [
                    Meeting(days: [.tuesday, .thursday], start: "5:30 PM", end: "6:45 PM", building: "BLOC", room: "1O9")
                ])
            ])
        ]

        for fixture in fixtures {
            let source = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
                .appendingPathComponent("Fixtures").appendingPathComponent(fixture.file)
            let data = try Data(contentsOf: source)
            do {
                let result = try await ScheduleImageImportService().analyze(
                    data, currentTerm: ScheduleSeed.term, useAppleIntelligence: false
                )
                XCTAssertFalse(result.usedAppleIntelligence)
                report(fixture: fixture, draft: result.draft, lineCount: result.recognizedLineCount)
            } catch {
                print("OCR_EVAL \(fixture.file): analysis failed: \(error.localizedDescription)")
                if fixture.file == "clean-light.png" { XCTFail("Clean synthetic screenshot was unreadable: \(error)") }
            }
        }
    }

    private func report(fixture: Fixture, draft: ScheduleDraft, lineCount: Int) {
        let fieldNames = ["courseCode", "title", "section", "weekdays", "start", "end", "building", "room"]
        var total: [String: Int] = [:]
        var correct: [String: Int] = [:]
        var omissions: [String] = []
        func score(_ field: String, _ matched: Bool, _ context: String) {
            total[field, default: 0] += 1
            if matched { correct[field, default: 0] += 1 }
            else { omissions.append("\(context).\(field)") }
        }
        func normalizedCode(_ code: String) -> String {
            code.uppercased().filter { $0.isLetter || $0.isNumber }
        }

        for expected in fixture.courses {
            let actual = draft.courses.first { normalizedCode($0.code) == normalizedCode(expected.code) && $0.section == expected.section }
            score("courseCode", actual != nil, expected.code)
            score("title", actual?.title.caseInsensitiveCompare(expected.title) == .orderedSame, expected.code)
            score("section", actual?.section == expected.section, expected.code)
            for (index, meeting) in expected.meetings.enumerated() {
                let found = actual?.meetings.indices.contains(index) == true ? actual?.meetings[index] : nil
                let context = "\(expected.code)#\(index + 1)"
                score("weekdays", found?.weekdays == meeting.days, context)
                score("start", found.flatMap { MeetingTime.parse($0.startTime) } == MeetingTime.parse(meeting.start), context)
                score("end", found.flatMap { MeetingTime.parse($0.endTime) } == MeetingTime.parse(meeting.end), context)
                score("building", found?.buildingCode == meeting.building, context)
                score("room", found?.room == meeting.room, context)
            }
        }
        let expectedCodes = Set(fixture.courses.map { normalizedCode($0.code) })
        let falseCourses = draft.courses.filter { !$0.code.isEmpty && !expectedCodes.contains(normalizedCode($0.code)) }.count
        let falseMeetings = draft.courses.reduce(0) { count, course in
            let expectedCount = fixture.courses.first { normalizedCode($0.code) == normalizedCode(course.code) }?.meetings.count ?? 0
            let nonempty = course.meetings.filter { !$0.weekdays.isEmpty || !$0.startTime.isEmpty || !$0.endTime.isEmpty }.count
            return count + max(0, nonempty - expectedCount)
        }
        let fields = fieldNames.map { "\($0)=\(correct[$0, default: 0])/\(total[$0, default: 0])" }.joined(separator: " ")
        print("OCR_EVAL \(fixture.file): lines=\(lineCount) \(fields) omitted=[\(omissions.joined(separator: ","))] falseCourses=\(falseCourses) falseMeetings=\(falseMeetings)")
    }
}
